"""empty message

Revision ID: 0a71f1c07dba
Revises: 185eb6252e7a
Create Date: 2025-02-13 01:32:59.902460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a71f1c07dba'
down_revision = '185eb6252e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_games')
    # ### end Alembic commands ###
