"""Added disliked_status to UserGame table

Revision ID: 1e6948620dc2
Revises: a7c3227682fb
Create Date: 2025-04-02 16:39:45.711013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6948620dc2'
down_revision = 'a7c3227682fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disliked_status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_column('disliked_status')

    # ### end Alembic commands ###
