"""Updated column names

Revision ID: 2aa37e46612f
Revises: 9bb79aa54300
Create Date: 2025-04-14 19:56:49.847853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa37e46612f'
down_revision = '9bb79aa54300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_pc_windows', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('show_xbox_series_x_s', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('show_nintendo_switch', sa.Boolean(), nullable=False))
        batch_op.drop_column('show_xbox_series_sx')
        batch_op.drop_column('show_switch')
        batch_op.drop_column('show_windows')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_windows', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('show_switch', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('show_xbox_series_sx', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('show_nintendo_switch')
        batch_op.drop_column('show_xbox_series_x_s')
        batch_op.drop_column('show_pc_windows')

    # ### end Alembic commands ###
