"""Added more platforms

Revision ID: 2cb619bacdc8
Revises: bcc12b64747b
Create Date: 2025-04-12 16:10:57.793962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb619bacdc8'
down_revision = 'bcc12b64747b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_windows', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('show_playstation_5', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('show_xbox_series_sx', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('show_playstation_4', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('show_xbox_one', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('show_linux', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('show_mac', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.drop_column('show_pc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_pc', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('show_mac')
        batch_op.drop_column('show_linux')
        batch_op.drop_column('show_xbox_one')
        batch_op.drop_column('show_playstation_4')
        batch_op.drop_column('show_xbox_series_sx')
        batch_op.drop_column('show_playstation_5')
        batch_op.drop_column('show_windows')

    # ### end Alembic commands ###
