"""Removed xbox table from user model

Revision ID: 9bb79aa54300
Revises: 2cb619bacdc8
Create Date: 2025-04-13 21:13:50.018405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb79aa54300'
down_revision = '2cb619bacdc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_xbox')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_xbox', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
