"""empty message

Revision ID: a7c3227682fb
Revises: 0a71f1c07dba
Create Date: 2025-02-13 21:30:31.605483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c3227682fb'
down_revision = '0a71f1c07dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('played_status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('favorited_status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_games', schema=None) as batch_op:
        batch_op.drop_column('favorited_status')
        batch_op.drop_column('played_status')
        batch_op.drop_column('liked_status')

    # ### end Alembic commands ###
